### ISSUE TITLE
About preparing data set

### ISSUE THREAD

**Issue by xuncpp** [VITA-Group/FSGS#49]
First of all, thank the author for your good work, but I encountered some problems on preparing the data set. What I needed to declare was that I was running under the Windows system and made some changes to the original code.
1. I got the two files of Images and Sparse according to the experience of Gauss's preparation data set in the past.
2. I downloaded the published 3Views data on Google Cloud.
3. Then run the code in LLFF and get the poses_bounds.npy file.
The error message is as follows：

`Reading camera 1/34Traceback (most recent call last):
  File "D:\project\FSGS\train.py", line 279, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args)
  File "D:\project\FSGS\train.py", line 44, in training
    scene = Scene(args, gaussians, shuffle=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\FSGS\scene\__init__.py", line 48, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval, args.n_views)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\FSGS\scene\dataset_readers.py", line 291, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\FSGS\scene\dataset_readers.py", line 196, in readColmapCameras
    rgb_path = rgb_mapping[idx]   # os.path.join(images_folder, rgb_mapping[idx])
               ~~~~~~~~~~~^^^^^
IndexError: list index out of range`

Report error information shows that list index out of range.
I checked the original code, and I also checked the number of Images and the number of images and the number of sparse\ images.txt. The number of them is the same, so I don't understand where there is something wrong.
I hope someone can answer my questions or share a complete data that can run successfully. Thank you very much!

**Comment by xuncpp** [comment]
The problem has been solved, I hope it can help people with the same problem.
In arguments/__init__.py, the author's default self._images = "images_8", you can change it to your own image folder name.
