### ISSUE TITLE
Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]

### ISSUE THREAD

**Issue by 123456xuan** [VITA-Group/FSGS#59]
Hi, thanks for the code you provided, I solved a lot of things in this code. However, the following problem occurred when I used my own D-bit data set. I checked many parts of the code that could be modified, but still couldn't find a solution, so please help me to answer this problem, thank you very much.

Traceback (most recent call last):
  File "/home/root/FSGS/train.py", line 282, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args)
  File "/home/root/FSGS/train.py", line 139, in training
    loss.backward()
  File "/opt/anaconda3/envs/3dgs/lib/python3.9/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/opt/anaconda3/envs/3dgs/lib/python3.9/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]
Training progress:   0%|                                                                      | 0/10000 [00:00<?, ?it/s]

**Comment by HannahHaensen** [comment]
did you fix it @123456xuan

**Comment by HannahHaensen** [comment]
ok probably that should be the issue https://github.com/VITA-Group/FSGS/issues/9

**Comment by HannahHaensen** [comment]
Loading Training Cameras [02/12 15:53:13]
24it [00:00, 44.71it/s]
Loading Test Cameras [02/12 15:53:13]
35it [00:00, 64.50it/s]
Number of points at initialisation :  0 [02/12 15:53:16]
